apiVersion: v1
kind: PersistentVolume
metadata:
  name: alarm-logs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/mcdev/Alarm_logs"
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alarm-logs-pvc
  namespace: mdvr-stag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdvr-alarm-deployment
  namespace: mdvr-stag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdvr-alarm
  template:
    metadata:
      labels:
        app: mdvr-alarm
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: storage
                operator: In
                values:
                - available
      containers:
      - name: mdvr-alarm-container
        image: 9989228601/comms_alarm_4050:9
        volumeMounts:
        - name: logs-volume
          mountPath: /usr/app/alarm_4050/Alarm_4050_logs
      volumes:
      - name: logs-volume
        persistentVolumeClaim:
          claimName: alarm-logs-pvc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 30
  revisionHistoryLimit: 3

---
apiVersion: v1
kind: Service
metadata:
  name: mdvr-alarm-service
  namespace: mdvr-stag
spec:
  type: ClusterIP
  selector:
    app: mdvr-alarm
  ports:
    - protocol: TCP
      port: 8013  # Example port number, replace with your actual port
      targetPort: 8013  # Example target port, replace with your actual target port



# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mdvr-alarm-deployment
#   namespace: mdvr-stag
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mdvr-alarm
#   template:
#     metadata:
#       labels:
#         app: mdvr-alarm
#     spec:
#       containers:
#       - name: mdvr-alarm-container
#         image: 9989228601/comms_alarm_4050:9
#         volumeMounts:
#         - name: logs-volume
#           mountPath: /usr/app/alarm_4050/Alarm_4050_logs
#       volumes:
#       - name: logs-volume
#         persistentVolumeClaim:
#           claimName: alarm-logs-pvc
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxSurge: 1
#       maxUnavailable: 0
#   minReadySeconds: 30
#   revisionHistoryLimit: 3


# ---
# apiVersion: v1
# kind: ResourceQuota
# metadata:
#   name: mdvr-alarm-quota
#   namespace: mdvr-stag
# spec:
#   hard:
#     pods: 2
#   requests:
#       cpu: "500m"
#       memory: "512Mi"
#   limits:
#       cpu: "1"
#       memory: "1Gi"
# ---
# apiVersion: autoscaling/v2beta2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: mdvr-alarm-hpa
#   namespace: mdvr-stag
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: mdvr-alarm-deployment
#   minReplicas: 1
#   maxReplicas: 3
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 50
